### ISSUE TITLE
Scale is not assigned to d3 object when it's not global

### ISSUE THREAD

**Issue by 3amprogrammer** [schnerd/d3-scale-cluster#3]
First of all I want to thank you a ton for this project, you have saved the day for me 👍 

However, I'm using RequireJS and d3 is being loaded as a dependency to every module that needs it. As far as I know you are not requiring it as a dependency, just checking if it's globally accessible
```
if (typeof d3 === 'object') {
  d3.scaleCluster = d3scaleCluster;
}
```

Is there any reason for this? For now I am requiring this alongside d3js and it's working just fine.

**Comment by schnerd** [comment]
I suppose the main reason is that this module technically has zero dependencies on d3 or any d3 utilities (d3-array, d3-format, etc.). In fact it could probably just be renamed `scale-cluster` and used independently of d3, although I imagine the vast majority of people will be using it with d3.

Adding it to the global d3 is primarily a convenience to create an API similar to the other scales like d3.scaleQuantile, etc. If you'd like to submit a pull request that somehow adds it to d3 when included by RequireJS, go for it! (as long as d3 remains a non-dependency)

Also, sorry for the late reply!

**Comment by schnerd** [comment]
Closing old issue
