### ISSUE TITLE
npm install fails on node-gyp rebuild with "gyp: No Xcode or CLT version detected!"

### ISSUE THREAD

**Issue by prasanthmaran1** [schnerd/d3-scale-cluster#7]
error code

```
> ckmeans@1.0.1 install /Users/project/node_modules/ckmeans
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.0.0
gyp ERR! command "/usr/local/Cellar/node/8.1.3/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/project/node_modules/ckmeans
gyp ERR! node -v v7.0.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN facilio@0.0.1 No repository field.
npm WARN facilio@0.0.1 No license field.
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/Cellar/node/8.1.3/bin/node" "/usr/local/bin/npm" "install" "--save" "d3-scale-cluster"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! ckmeans@1.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ckmeans@1.0.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ckmeans package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ckmeans
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ckmeans
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/project/npm-debug.log
```

**Comment by schnerd** [comment]
@prasanthmaran1 this library contains a native addon for extra performance in node environments, what this means is that you should have a c compiler installed on your system. This is fairly common in the node ecosystem.

See instructions here: https://github.com/nodejs/node-gyp#on-macos

In most cases this is as easy as running `xcode-select --install` on your mac.

Let me know if that works.

**Comment by prasanthmaran1** [comment]
Thanks @schnerd package installed successfully...

**Comment by gilbertomangones** [comment]
perfect work for me. using xcode-select --install on mac. Thank you.

**Comment by paul4156** [comment]
I had to re-install the xcode tools for some weird reason...

```
sudo rm -rf $(xcode-select -print-path)
xcode-select --install
```

That is listed in the bottom of the guide (https://github.com/nodejs/node-gyp/blob/master/macOS_Catalina.md). So thank you!

**Comment by tinker-li** [comment]
> I had to re-install the xcode tools for some weird reason...
> 
> ```
> sudo rm -rf $(xcode-select -print-path)
> xcode-select --install
> ```
> 
> That is listed in the bottom of the guide (https://github.com/nodejs/node-gyp/blob/master/macOS_Catalina.md). So thank you!

I do as this, too.

**Comment by Fil** [comment]
I wouldn't ever trust a `sudo rm -rf $(smth)` command. However, doing it it two steps solved the problem for me also:

```
> xcode-select -print-path
/Library/Developer/CommandLineTools
> sudo rm -rf /Library/Developer/CommandLineTools
```

**Comment by SK-CSE** [comment]
following step help me to resolve this issue on  Mac Catalina OS

```
sudo rm -rf $(xcode-select -print-path)
```
```
xcode-select --install
```
```
/usr/sbin/pkgutil --packages | grep CL
```
```
sudo npm install -g node-gyp
```

**Comment by aerolalit** [comment]
> I had to re-install the xcode tools for some weird reason...
> 
> ```
> sudo rm -rf $(xcode-select -print-path)
> xcode-select --install
> ```
> 
> That is listed in the bottom of the guide (https://github.com/nodejs/node-gyp/blob/master/macOS_Catalina.md). So thank you!

This worked for me in MacOs catalina.

**Comment by wangxiaocuo** [comment]
> I had to re-install the xcode tools for some weird reason...
> 
> ```
> sudo rm -rf $(xcode-select -print-path)
> xcode-select --install
> ```
> 
> That is listed in the bottom of the guide (https://github.com/nodejs/node-gyp/blob/master/macOS_Catalina.md). So thank you!

Thank you !!! very much

**Comment by bengotow** [comment]
I hate that reinstalling the Xcode tools worked, but it did.

I bought a brand new MBP today and installed Xcode on it for the first time a few hours ago (and xcode-select reported the tools were already installed). Really have no idea why this is necessary. Thanks, internet friends 🙏

**Comment by NickPepper** [comment]
It’s time for them to rename their X-code to XXX-code...
Thank you very much, SK-CSE !
`/usr/sbin/pkgutil --packages | grep CL`
resolves the issue on Catalina.

**Comment by nwittstruck** [comment]
If you don't want to re-install xcode, you can also point xcode-select to the existing installation:

`sudo xcode-select -s /Applications/Xcode.app/Contents/Developer`

Make sure to open xcode at least once after installation to accept the terms.

**Comment by goto1** [comment]
I had a similar issue with a different package:
```sh
node-gyp rebuild
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
gyp: No Xcode or CLT version detected!
gyp ERR! configure error
```

Running on `macOS Catalina 10.15.2`, I tried:
```sh
$ xcode-select --install
xcode-select: error: command line tools are already installed, 
use "Software Update" to install updates
```

Fixed it by running the following:
```sh
$ [sudo] xcode-select --reset
```

**Comment by thompcd** [comment]
I'm currently on Catalina, following the reinstall commands:
```
sudo rm -rf $(xcode-select -print-path)
xcode-select --install
```

I use fish as a shell and it didn't like the $( ...) command. Just wanted to mention that to work around it quickly, I just went into the Vscode terminal window and in the shell dropdown choose 'select default shell', choose a new shell from the top list (I used bash), then hit the '+' to open a new bash console. Then I could follow the commands directly without wrecking my fish shell setup.

**Comment by kn100** [comment]
> I'm currently on Catalina, following the reinstall commands:
> 
> ```
> sudo rm -rf $(xcode-select -print-path)
> xcode-select --install
> ```
> 
> I use fish as a shell and it didn't like the $( ...) command. Just wanted to mention that to work around it quickly, I just went into the Vscode terminal window and in the shell dropdown choose 'select default shell', choose a new shell from the top list (I used bash), then hit the '+' to open a new bash console. Then I could follow the commands directly without wrecking my fish shell setup.

In Fish just drop the dollar!
```
sudo rm -rf (xcode-select -print-path)
xcode-select --install
```

**Comment by tomboland-vocovo** [comment]
Please don't run ```rm -rf $(any command at all)```, ever!

Just run ```xcode-select -print-path```, confirm the path, then ```sudo rm -rf that_path```.  What if the command errored and output a single / or the path to your home directory.  Destruction would ensue!  Fundamentally, the advice to reinstall xcode is good.  Having to do it at all is not so good :/

**Comment by nikhilmisra63** [comment]
sudo rm -rf $(xcode-select -print-path)
xcode-select --install
yarn install 

works for me

**Comment by Rakkoc** [comment]
> > I'm currently on Catalina, following the reinstall commands:
> > ```
> > sudo rm -rf $(xcode-select -print-path)
> > xcode-select --install
> > ```
> > 
> > 
> > I use fish as a shell and it didn't like the $( ...) command. Just wanted to mention that to work around it quickly, I just went into the Vscode terminal window and in the shell dropdown choose 'select default shell', choose a new shell from the top list (I used bash), then hit the '+' to open a new bash console. Then I could follow the commands directly without wrecking my fish shell setup.
> 
> In Fish just drop the dollar!
> 
> ```
> sudo rm -rf (xcode-select -print-path)
> xcode-select --install
> ```

thank you. thats solv my problem.

**Comment by douglasrcjames** [comment]
Looks like `sudo xcode-select --reset` fixed my issue without needing to reinstall Xcode entirely.

**Comment by ranasingh** [comment]
This fixed it for me:
First reset: `sudo xcode-select -r`
Then accept license: `sudo xcodebuild -license`

**Comment by Katalyst33** [comment]
I am having this error and nothing here has worked.

**Comment by IefCuynen** [comment]
> I am having this error and nothing here has worked.

Had the same issue.
Even after

```
sudo rm -rf (xcode-select -print-path)
xcode-select --install
```
I got the message
```
xcode-select: error: command line tools are already installed, 
use "Software Update" to install updates
```
Even `sudo xcode-select --reset` did not fix anything and basically I ended up with a partly uninstalled xcode so I couldn't reinstall xcode from the app store too.

I used [https://nektony.com/mac-app-cleaner](url) to fully uninstall xcode and reinstalled xcode again from the app store.
That worked out great.

Hope it helps to solve your problem too

**Comment by dazuaz** [comment]
Avoid using this command ever
`sudo rm -rf ..`
For mac you can use something like `trash` installed with `brew install trash`
then use it for all your command line deletions! i.e.
`trash (xcode-select -print-path)`

**Comment by enderphan94** [comment]
> I had a similar issue with a different package:
> 
> ```shell
> node-gyp rebuild
> No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
> No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
> No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
> gyp: No Xcode or CLT version detected!
> gyp ERR! configure error
> ```
> 
> Running on `macOS Catalina 10.15.2`, I tried:
> 
> ```shell
> $ xcode-select --install
> xcode-select: error: command line tools are already installed, 
> use "Software Update" to install updates
> ```
> 
> Fixed it by running the following:
> 
> ```shell
> $ [sudo] xcode-select --reset
> ```

This solved my issue. Thanks

**Comment by an00bhav** [comment]
Yep same for me!! :) Thx for reporting.

**Comment by kevinnguy** [comment]
> I had a similar issue with a different package:
> 
> ```shell
> node-gyp rebuild
> No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
> No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
> No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
> gyp: No Xcode or CLT version detected!
> gyp ERR! configure error
> ```
> 
> Running on `macOS Catalina 10.15.2`, I tried:
> 
> ```shell
> $ xcode-select --install
> xcode-select: error: command line tools are already installed, 
> use "Software Update" to install updates
> ```
> 
> Fixed it by running the following:
> 
> ```shell
> $ [sudo] xcode-select --reset
> ```

This worked for me by only having to run `xcode-select --reset`. I would try this first before removing anything!

**Comment by avivasyuta** [comment]
> I had to re-install the xcode tools for some weird reason...
> 
> ```
> sudo rm -rf $(xcode-select -print-path)
> xcode-select --install
> ```
> 
> That is listed in the bottom of the guide (https://github.com/nodejs/node-gyp/blob/master/macOS_Catalina.md). So thank you!

Reinstall works for me on mac OS Catalina

**Comment by igl** [comment]
`sudo xcode-select --reset` did the trick too

**Comment by vsnthdev** [comment]
> I had to re-install the xcode tools for some weird reason...
> 
> ```
> sudo rm -rf $(xcode-select -print-path)
> xcode-select --install
> ```
> 
> That is listed in the bottom of the guide (https://github.com/nodejs/node-gyp/blob/master/macOS_Catalina.md). So thank you!

This helped me after updating from macOS 10.15.2 to 10.15.3

**Comment by dpashutskii** [comment]
The only thing which helps me is to install CLI Tools manually from the Apple developers website. But I have to do this every time I update my macOS. It's horrible! :(

**Comment by SiddhantSwami** [comment]
> > I had to re-install the xcode tools for some weird reason...
> > ```
> > sudo rm -rf $(xcode-select -print-path)
> > xcode-select --install
> > ```
> > 
> > 
> > That is listed in the bottom of the guide (https://github.com/nodejs/node-gyp/blob/master/macOS_Catalina.md). So thank you!
> 
> This worked for me in MacOs catalina.

+1

**Comment by kistars** [comment]
> @prasanthmaran1 this library contains a native addon for extra performance in node environments, what this means is that you should have a c compiler installed on your system. This is fairly common in the node ecosystem.
> 
> See instructions here: https://github.com/nodejs/node-gyp#on-macos
> 
> In most cases this is as easy as running `xcode-select --install` on your mac.
> 
> Let me know if that works.

Thanks for your help! It works on my machine now!

**Comment by danbilauca** [comment]
I deleted the Xcode as the previous answers say and I got a failure while installing it back. Not sure if everything is fine yet, but what really worked for me was to delete the `package-lock.json` and update `grunt-sass` dependency from `^1.0.0` to `^2.1.0`

I'm on MacOS Catalina `10.15.3`

**Comment by ilias-t** [comment]
Try `sudo xcodebuild -license accept`

**Comment by sumit0708** [comment]
Reinstalled by 'xcode-select --install' but still facing the issue.
What to do as am using latest MacOS Catalina  10.15.4

**Comment by SK-CSE** [comment]
> following step help me to resolve this issue on Mac Catalina OS
> 
> ```
> sudo rm -rf $(xcode-select -print-path)
> ```
> 
> ```
> xcode-select --install
> ```
> 
> ```
> /usr/sbin/pkgutil --packages | grep CL
> ```
> 
> ```
> sudo npm install -g node-gyp
> ```

@sumit0708 have you tried these above steps ☝️

**Comment by nigilan** [comment]
Updating to macOS to latest version fixed this issue for me. macOS - 10.15.4 . Node - v12.16.1. npm - v6.13.4.

**Comment by sgentile** [comment]
Getting same, 

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

**Comment by davidcalhoun** [comment]
I previously went through the steps to fix the issue via command line, but the exact same issue popped up again later.  This time I installed via the Xcode interface, which takes you to https://developer.apple.com/download/more/?=for%20Xcode where you can download the latest tools under `Command Line Tools for Xcode x.x`.  Fixed it for now, hopefully for good.

EDIT: It's happened again after updating Xcode.  Looks like you just need to open Xcode, get prompted with "Install additional required components?", and click `Install`.

**Comment by mnishizawa** [comment]
> following step help me to resolve this issue on Mac Catalina OS
> 
> ```
> sudo rm -rf $(xcode-select -print-path)
> ```
> 
> ```
> xcode-select --install
> ```
> 
> ```
> /usr/sbin/pkgutil --packages | grep CL
> ```
> 
> ```
> sudo npm install -g node-gyp
> ```

I tried uninstalling and reinstalling, that didn't work.  The global node-gyp install made it work.

**Comment by nadnoslen** [comment]
This issue keeps coming up for me every so often; likely tied to minor upgrades to OS X.  `xcode-select --reset` does not seem to ever work for me.  I end up resorting to a fresh install of the command line tools:

```shell
trash $(xcode-select -print-path)
xcode-select --install
# wait ten minutes... (◔_◔)
```

Good luck all!

**Comment by sscoville-rbx** [comment]
> `sudo xcode-select --reset` did the trick too

This is the only thing that fixes it for me.

**Comment by tr1s** [comment]
My xcode recently updated and I ran into this problem for the second time. Instead of re-installing which I did the first time, I ran `sudo xcode-select -s /Applications/Xcode.app/Contents/Developer` to point to the existing install location like @nwittstruck mentioned. 

Worked perfect, thanks!

**Comment by sumantaparida** [comment]
> perfect work for me. using xcode-select --install on mac. Thank you.

not work

**Comment by codeater7** [comment]
Time and again, I have to install x-code what is the main issue??

**Comment by wangxiaocuo** [comment]
> > I am having this error and nothing here has worked.
> 
> Had the same issue.
> Even after
> 
> ```
> sudo rm -rf (xcode-select -print-path)
> xcode-select --install
> ```
> 
> I got the message
> 
> ```
> xcode-select: error: command line tools are already installed, 
> use "Software Update" to install updates
> ```
> 
> Even `sudo xcode-select --reset` did not fix anything and basically I ended up with a partly uninstalled xcode so I couldn't reinstall xcode from the app store too.
> 
> I used [https://nektony.com/mac-app-cleaner](url) to fully uninstall xcode and reinstalled xcode again from the app store.
> That worked out great.
> 
> Hope it helps to solve your problem too

Sometimes it works, sometimes it doesn't. 
So I suggest you use **`yarn`** to avoid the pain.
Or you can choose to use `less` instead of `SCSS`.

**Comment by gschema** [comment]
@prasanthmaran1 hey mate, can you add this link:

[The solution for the node-gyp problem/error on macOS Catalina "No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'."](https://github.com/nodejs/node-gyp/blob/master/macOS_Catalina.md)

In similar fashion like @joe-nano did at the top of his initial post here:

https://github.com/nodejs/node-gyp/issues/1927

My issue background:

On my machine `node-gyp` got broken totally randomly and have no idea what to connect that break/corruption to. The system works perfectly fine and has 0 issues. After a restart it got reported as broken after running `yarn`. It was installed and present in the system but installation was corrupted for some reason. Interesting.

**Comment by atipugin** [comment]
Second time a row Catalina updates (10.15, 10.15.1) break CLT. Removing existing dir and re-installing CLT works, but it's pretty annoying.

**Comment by bohehe** [comment]
> I had to re-install the xcode tools for some weird reason...
> 
> ```
> sudo rm -rf $(xcode-select -print-path)
> xcode-select --install
> ```
> 
> That is listed in the bottom of the guide (https://github.com/nodejs/node-gyp/blob/master/macOS_Catalina.md). So thank you!

Save my life, thank you!

**Comment by omjha1505** [comment]
https://github.com/nodejs/node-gyp/blob/master/macOS_Catalina.md.  : this works for me. thanks

**Comment by m-a-r-c-e-l-i-n-o** [comment]
Only thing that worked for me was a comment by **_inglkruiz_** on here: https://github.com/nodejs/node-gyp/issues/1927

**Comment by halkemist** [comment]
If you have a server response problem after `xcode-select --install` command.

Download the **Command Line Tools for Xcode** directly from [https://developer.apple.com/download/more/](https://developer.apple.com/download/more/)

**Comment by kaiwoods** [comment]
Time and time again I have to reinstall these tools, it's getting to a point this is no longer a solution and simply a work-around until it happens again. Is there any information as to what the actual cause of the problem is...?

**Comment by kaiwoods** [comment]
I've fixed this by forcing npm to use a later version of node-gyp (at least version 7).

1. Install node-gyp globally `npm install -g node-gyp`
2. Confirm you're on a version 7 or higher `node-gyp -v`
3. Get the path to the script `which node-gyp`
4. Update npm config to use this version of node-gyp `npm config set node_gyp /path/from/previous/step`

This is hopefully a more permanent solution than always needing to re-install xcode-select tools. Unfortunately that is something I've found myself having to do time and time again.

The only gotcha is that, in my case (using nvm to manage my node version), when I update node, I'll have to update this config again. Still, I'd rather that than reinstall xcode-select every time.

Working good for me so far; YMMV.

**Comment by nadnoslen** [comment]
Thanks @kaiwoods.  I use asdf and bump into this as I dance around projects with different versions of node.  For my asdf world I needed to `asdf which node-gyp` to fetch the proper `node-gyp` path (regular `which` will give you the asdf shim).  Hope that helps asdf users.  And seriously, thanks @kaiwoods!!!

**Comment by AlexeySmolyaninov** [comment]
I have had an old node version after I have updated it to a new stable one it fixed my problem.

**Comment by Pearel-Skillate** [comment]
> following step help me to resolve this issue on Mac Catalina OS
> 
> ```
> sudo rm -rf $(xcode-select -print-path)
> ```
> 
> ```
> xcode-select --install
> ```
> 
> ```
> /usr/sbin/pkgutil --packages | grep CL
> ```
> 
> ```
> sudo npm install -g node-gyp
> ```

This worked perfectly!
